config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get 'home/about', to: 'homes#about', as: 'about'

  resources :books, only: [:update, :create, :index, :show, :destroy, :edit] do
      resource :favorite, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update]
  

 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image

 
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy                         
    redirect_back(fallback_location: books_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit]
  def index
    @books = Book.all 
    @book = Book.new  
    @user = current_user
    
  end

  def show
    @book = Book.new 
    @book_show = Book.find(params[:id])  # まず、表示する本を取得
    @user = @book_show.user  # 本の持ち主を取得
    @book_comment = BookComment.new
    
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @user = current_user # renderでindexに行くときに使用する
    @books = Book.all # renderでindexに行くときに使用する

    @book = Book.new(book_params)
    @book.user_id = current_user.id  # 現在のユーザーIDを設定
    
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice]="You have created book successfully."
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully.." 
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private
  # ストロングパラメータの設定
  
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: books_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: books_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit]
  def index
    @users=User.all
    
    @user = current_user
    @book = Book.new
  end



  def show
    @book = Book.new
    @user = User.find_by(id: params[:id])
    @books = @user.books
  end

  def edit
    @user = current_user
    
    
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully." 
      redirect_to @user
    else
      render :edit
    end
  
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info_and_new_book.html.erb
      <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %> <%= @book.errors.count == 1 ? 'error' : 'errors' %> prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <h2>User info</h2>
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, size: "100x100" %>
      <% else %>
        <%= image_tag 'default-image.jpg', size: "100x100" %>
      <% end %>
      
      <table class="table mb-5">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      
      <div class="row"> 
      <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary  btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, url: '/books', method: :post  do |f| %>
        <p>Title</p>
        <%= f.text_field :title , class: "form-control"%>
	
        <p>Opinion</p>
        <%= f.text_area :body , class: "form-control"%>
	
        <%= f.submit 'Create Book', class: "btn btn-success mt-3"%>
      <% end %>

app/views/books/edit.html.erb
<div class='container pt-3 px-sm-0'>
   <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>Editing Book</h1>
            <% if @book.errors.any? %>
                <h3>
                    <%= @book.errors.count %> <%= @book.errors.count == 1 ? 'error' : 'errors' %> prohibited this obj from being saved:
                </h3>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>

              <%= form_with model: @book, url: book_path(@book), method: :patch do |f| %>
                  <div class="form-group">
                      <p>Title</p>
                      <%= f.text_field :title  , class: "form-control"%>
                  </div>

                  <div class="form-group">
                      <p>Opinion</p>
                      <%= f.text_area :body , class: "form-control"%>
                  </div>
                  <%= f.submit 'Update Book' ,class: "btn btn-success mb-3"%>

                <% end %>
                <td><%= link_to "Show" ,book_path(@book.id)%></td>
                | 
                <td><%= link_to "Back" ,books_path%></td>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 pt-3 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user_info_and_new_book' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Body</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
            <td>
            <% if book.user.profile_image.attached? %>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag book.user.profile_image, size: "80x80" %>
              <% end %>
            <% else %>
              <%= link_to user_path(book.user.id) do %>
                <%= image_tag 'default-image.jpg', size: "80x80" %>
              <% end %>
            <% end %>
          </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>

              <td>
                <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorite_path(book), method: :delete do %>
                      <i class="fa-solid fa-heart" style="color: #ff2600;"></i><span style="color: red;"><%= book.favorites.count %></span>
                    <% end %>
                    
                <% else %>
                  <%= link_to book_favorite_path(book), method: :post do %>
                    <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                  <% end %>
              <% end %>   
              </td>

              <td>コメント数：<%= book.book_comments.count %></td>

            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 pt-3 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user_info_and_new_book' %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <% if @book_show.user.profile_image.attached? %>
                <%= link_to user_path(@book_show.user.id) do %>
                  <%= image_tag @book_show.user.profile_image, size: "100x100" %>
                <% end %>
              <% else %>
                <%= link_to user_path(@book_show.user.id) do %>
                  <%= image_tag 'default-image.jpg', size: "100x100" %>
                <% end %>
              <% end %>

             
              <br>
              <%= link_to @book_show.user.name, user_path(@book_show.user.id) %>
            </td>
            <td><%= link_to @book_show.title, book_path(@book_show.id) %></td>
            <td><%= @book_show.body %></td>

            <td>
                <% if @book_show.favorited_by?(current_user) %>
                    <%= link_to book_favorite_path(@book_show), method: :delete do %>
                      <i class="fa-solid fa-heart" style="color: #ff2600;"></i><span style="color: red;"><%= @book_show.favorites.count %></span>
                    <% end %>
                    
                <% else %>
                  <%= link_to book_favorite_path(@book_show), method: :post do %>
                    <i class="fa-solid fa-heart"></i><%= @book_show.favorites.count %>
                  <% end %>
              <% end %>   
            </td>
            <td>コメント数：<%= @book_show.book_comments.count %></td>

            <% if @book_show.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book_show.id), class: "btn btn-success btn-sm" %></td>
              <td><%= link_to "Destroy", book_path(@book_show.id), class: "btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <div>
      <table>
        <tbody>
          <% @book_show.book_comments.each do |book_comment| %>
            <tr>
              <!-- アイコン表示 -->
              <td>
                <% if book_comment.user.profile_image.attached? %>
                  <%= link_to user_path(book_comment.user.id) do %>
                    <%= image_tag book_comment.user.profile_image, size: "100x100" %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(book_comment.user.id) do %>
                    <%= image_tag 'default-image.jpg', size: "100x100" %>
                  <% end %>
                <% end %>
              </td>
    
              <!-- コメント表示 -->
              <td><%= book_comment.comment %></td>
    
              <!-- 削除ボタン（ログインユーザーのみ） -->
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to "Destroy", book_book_comment_path(@book_show, book_comment), 
                    class: "btn btn-danger btn-sm", method: :delete %>
                <% end %>
              </td>
            </tr>
            <!-- ユーザー名（画像の下に表示する場合は別の場所に移動） -->
            <tr>
              <td>
                <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<div>
  <%= form_with model: [@book_show, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', style: 'width: 100%;' %>
    <div><%= f.submit "送信" %></div>
  <% end %>
</div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container pt-3 px-sm-0'>
      <div class='row'>
            <div class="mx-auto">
                  <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
            </div>
      </div>
</div>

app/views/homes/top.html.erb
<div class='container px-3 pt-3'>
  	  <div class='row'>
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
            <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>
                   <div class="col-10 mx-auto">
                        <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
                        <%= link_to 'Sign up', new_user_registration_path, class:  "btn btn-success btn-sm btn-block" %>
                  </div>
            </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/8380560953.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header class="header_back">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container">
        <a class="navbar-brand text-light" href="/">Bookers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
              <li>
                <a class="nav-link text-light" href="<%= user_path(current_user) %>">
                  <i class="fa-solid fa-home"></i> Home
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="<%= users_path %>">
                  <i class="fa-solid fa-users"></i> Users
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="<%= books_path %>">
                  <i class="fa-solid fa-book-open"></i> Books
                </a>
              </li>
              <li>
                <a class="nav-link text-light" rel="nofollow" data-method="delete" href="<%= destroy_user_session_path %>">
                  <i class="fa-solid fa-sign-out-alt"></i> Log out
                </a>
              </li>
              
            <% else %>
              <li>
                <a class="nav-link text-light" href="<%= root_path %>">
                  <i class="fa-solid fa-home"></i> Home
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="<%= about_path %>">
                  <i class="fa-solid fa-link"></i> About
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="<%= new_user_registration_path %>">
                  <i class="fa-solid fa-user-plus"></i> Sign up
                </a>
              </li>
              <li>
                <a class="nav-link text-light" href="<%= new_user_session_path %>">
                  <i class="fa-solid fa-right-to-bracket"></i> Log in
                </a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
  <%= yield %>
   </main>

  <footer>
    <div class='container mt-5'>
      <div class='row'>
        <div class='mx-auto'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
  
</html>

app/views/users/edit.html.erb
<div class='container pt-3 px-sm-0'>
   <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>
            <% if @user.errors.any? %>
                <h3>
                    <%= @user.errors.count %> <%= @user.errors.count == 1 ? 'error' : 'errors' %> prohibited this obj from being saved:
                </h3>
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>



              <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
                  <div class="form-group">
                      <p>Name</p>
                      <%= f.text_field :name  , class: "form-control"%>
                  </div>

                  <div class="form-group">
                      <p>Image</p>
                      <%= f.file_field :profile_image, accept: "image/*" %>
                  </div>

                  <div class="form-group">
                      <p>Introduction</p>
                      <%= f.text_area :introduction , class: "form-control"%>
                  </div>
                  <%= f.submit 'Update User' ,class: "btn btn-secondary"%>

                <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 pt-3 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user_info_and_new_book' %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.profile_image, size: "80x80" %>
                <% else %>
                  <%= image_tag 'default-image.jpg', size: "80x80" %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 pt-3 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/user_info_and_new_book' %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
              <% if book.user.profile_image.attached? %>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.profile_image, size: "80x80" %>
                <% end %>
              <% else %>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag 'default-image.jpg', size: "80x80" %>
                <% end %>
              <% end %>

              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorite_path(book), method: :delete do %>
                    <i class="fa-solid fa-heart" style="color: #ff2600;"></i>
                    <span style="color: red;"><%= book.favorites.count %></span>
                    <% end %>
                    
                <% else %>
                  <%= link_to book_favorite_path(book), method: :post do %>
                    <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                  <% end %>
              <% end %>   
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>